


















































# integer value

In [4]:
a=1
print(type(a))

<class 'int'>


In [5]:
a=-1
print(type(a))

<class 'int'>


In [6]:
a=100
print(type(a))

<class 'int'>


In [7]:
a=-12
print(type(a))

<class 'int'>


# float value

In [8]:
a=1.3
print(type(a))

<class 'float'>


In [9]:
a=0.5
print(type(a))

<class 'float'>


# string value

string is collection of charactor or "" (double quote) and '' (single quote)

In [10]:
a='abhishek'
print(type(a))

<class 'str'>


In [11]:
a='123'
print(type(a))

<class 'str'>


In [12]:
a="12.4"
print(type(a))

<class 'str'>


In [13]:
a="-12"
print(type(a))

<class 'str'>


how to find a no of charactor len (fuction)

In [17]:
a="12.34"
print(len(a))

5


In [18]:
a='-134'
print(len(a))

4


In [19]:
a='123_34'
print(len(a))

6


# boolean data type

boolean data only show in 'true ' and 'False'

In [20]:
a=True
print(type(a))

<class 'bool'>


In [21]:
a=False
print(type(a))

<class 'bool'>


In [22]:
a=male
print(type(a))

NameError: name 'male' is not defined

some exercise

In [23]:
12= intergar
12.34=float
'123'= string
'abhishek'=str
False=boolean
*&^%#@$*=invaild data type


SyntaxError: cannot assign to literal (3320437850.py, line 1)

In [24]:
a=2+3
print(a)

5


In [25]:
a='3+2'
print(a)

3+2


In [26]:
a='abhishek'
print(a)

abhishek


In [27]:
print(abhishek)

NameError: name 'abhishek' is not defined

In [28]:
print(1234)

1234


In [29]:
print(12.4)

12.4


In [32]:
print("abhishek")

abhishek


# variable

In [33]:
age=20
age=30
print(age)

30


In [34]:
age=20
print(age)
age=30

20


# variable limits

don't be start variable in number

In [35]:
1a=3
print(1a)

SyntaxError: invalid syntax (2682264507.py, line 1)

don't b allowed spece in variable

In [36]:
love dose=3
print(love dose)

SyntaxError: invalid syntax (4141019513.py, line 1)

only one syntex is allowed in variable _(under score) 

In [37]:
_love_3=12
print(_love_3)

12


don't allowed be function name is variable name

In [38]:
print=2
print(print)

TypeError: 'int' object is not callable

In [39]:
type=3
print(type)

TypeError: 'int' object is not callable

how to assigen a variable and value in single line

In [6]:
a=name,age,sex='nikhil',28,"male"
print(a)

('nikhil', 28, 'male')


In [1]:
country='india'
flag='india'
citizen='india'
print(country,flag,citizen)


india india india


In [4]:
country,flag,citizen="india"
print(country,flag,citize)

ValueError: too many values to unpack (expected 3)

# operator

In [8]:
age=220
b=5
v=age+b
print(f'the v value is-{v}')

the v value is-225


In [9]:
a=123
b=23
v=a+b-a-b
print(f"the value of v-{v}")

the value of v-0


division(/)-the division value gives alaways float number

In [10]:
a=10
b=5
v=a/b
print(f"v division value is-{v}")

v division value is-2.0


In [11]:
a=125
b=5
c=a/b
print(f'c division value is:{c}')

c division value is:25.0


Floor division(//)- the gives the value in only integer form

In [13]:
a=10
b=3
c=a//b
print(f"c floor division is:{c}")

c floor division is:3


In [14]:
a=15
b=2
v=a//b
print(f"v floor value is : {v}")

v floor value is : 7


mudelo function(%)-the gives reminder value in integer form

In [15]:
a=6
b=4
c=a%4
print(f"c mudelo value is : {c}")

c mudelo value is : 2


In [16]:
a=16
b=3
g=a%b
print(f" g mudelo value is: {g}")

 g mudelo value is: 1


exoponet

In [17]:
a=2**3
print(f" a exoponet value is: {a}")

 a exoponet value is: 8


In [21]:
s=4**4
print(f"s exoponet value is :{s}")

s exoponet value is :256


In [22]:
v=5**6
print(f"v exponet value is:{v}")

v exponet value is:15625


# Assiegement operator

=,=>,=<,!=

In [6]:
a=4
b=5

print(a==b)


False


In [7]:
a=3
b=7
c=a==b
print(c)


False


(>) greater then

In [8]:
a=6
b=3
c=a>b
print(c)

True


In [9]:
a=5
b=6
c=a>b
print(c)

False


In [10]:
a=8
b=7
c=a<b
print(c)

False


In [11]:
b=8
c=10
a=c<b
print(a)


False


In [12]:
a=5
b=7
c=a>=b
print(c)

False


In [13]:
a=10
b=12
c=a<=b
print(c)

True


In [14]:
a=12
b=14
c=20
a>b or b<=c and a<c

True

In [15]:
a=12
b=12.5
c=25
d=25.7
a<=c and a>=d and c>=a or a<=c

True

In [16]:
a=12
b=10
c=14
d=7
a>d and b>=c or c<=a or d>=a and d<=a

False

In [20]:
a=12
b=15
c=11
d=17
e=12
f=14
g=9
a>=b and a<=d and a>=g or b==c and b!=d or a>=f or not True or not False

True

# logical operator 

In [23]:
a=10
b=20
c=12
m=(a*b)+b+c*b
print(m)

460


In [1]:
x=19
y=10
z=50
w=x+y-z
print(w)

-21


In [2]:
x=2
y=2
z=2
p=2
a=x-y*z**p
print(a)

-6


In [3]:
x=3
y=3
z=3
p=3
a=x+y-z*p**x
print(a)

-75


# not operator

In [4]:
a=not(7>3)
print(a)

False


In [6]:
a=3
b=4
c=5
a>b and a<=c or c!=a and not False

True

In [7]:
b=not(7<=8)
print(b)

False


In [8]:
a=34
b=45
c=20
d=10
a<=c and b>=d or a>=d or not False

True

In [ ]:
# 

# ep5 string

# + ,* this artmetric oprator use in string 

In [10]:
print('python'+ 'data')

pythondata


In [11]:
print("python"*"data")

TypeError: can't multiply sequence by non-int of type 'str'

using in + artmetic oprator in same data type in string cocateration..ex- print("nikhil"+ "pal")= nikhilpal

In [12]:
print('nikhil' + '23')

nikhil23


In [13]:
print('123'+"nikhil")

123nikhil


In [15]:
print("123"+ "123")

123123


# * use in string

In [4]:
name='nikhil'
m=5
g=name * m
print(g)

nikhilnikhilnikhilnikhilnikhil


In [5]:
name="nikhilpal"
m=10
p=name * m
print(p)

nikhilpalnikhilpalnikhilpalnikhilpalnikhilpalnikhilpalnikhilpalnikhilpalnikhilpalnikhilpal


In [6]:
print("nikhilpal"*12)

nikhilpalnikhilpalnikhilpalnikhilpalnikhilpalnikhilpalnikhilpalnikhilpalnikhilpalnikhilpalnikhilpalnikhilpal


In [7]:
print("123"*12)

123123123123123123123123123123123123


In [8]:
print("123"*12.5)

TypeError: can't multiply sequence by non-int of type 'float'

In [9]:
print("nikhil"*1.5)

TypeError: can't multiply sequence by non-int of type 'float'

# swapping of two values

In [12]:
#swaping of two values
a=10
b=20
#swaping value guess 
c=10
#puting value cross put
a=b
b=c
print(a,b)


20 10


In [14]:
##second method of swapping value

In [15]:
a=10
b=20
a,b=b,a
print(a,b)

20 10


opration of string under is called formatted string

In [18]:
p=1200
r=5
t=2
si=p*r*t/100
print(f"the simple intrest is-:{si}")

the simple intrest is-:120.0


In [19]:
x=123
b=23
a=x+b
print(f"the sum of two values-:{a}")

the sum of two values-:146


# input fuction 

In [23]:
name="harshit"
print(f"hi ,'{name}''")

hi ,'harshit''


In [26]:
a=input("entre the no of 1st:")
b=input("entre the no 2nd :")
add=a+b
print(f"the sum two no:{add}")

entre the no of 1st:12
entre the no 2nd :34
the sum two no:1234


# typecasting# int fuction

In [27]:
a=int(input("entre the no of 1st:"))
b=int(input("entre the no 2nd :"))
add=a+b
print(f"the sum two no:{add}")

entre the no of 1st:12
entre the no 2nd :3
the sum two no:15


In [30]:
a=int(input("entre the no of 1st:"))
b=int(input("entre the no 2nd :"))
c=int(input("entre the 3nd no:"))
add=a*b+c
print(f"the result of three no:{add}")

entre the no of 1st:12
entre the no 2nd :12
entre the 3nd no:20
the result of three no:164


# without typecasting

In [2]:
a=input("entre the value 1st:")
b=input("entre the value 2nd:")
c=a+b
print(f"the two no of sum:{c}")

entre the value 1st:12
entre the value 2nd:34
the two no of sum:1234


In [6]:
a=23
b="23"*3
print(f"the two times of print 23:{b}")

the two times of print 23:232323


# with typecasting int()

In [1]:
a=int(input("etre the 1nd no:"))
b=int(input("entre the 2nd no:"))
c=a+b-a*b
print(f" the value of c no is:{c}")

etre the 1nd no:20
entre the 2nd no:10
 the value of c no is:-170


# change in string,float,bool to int

In [2]:
a="123"
print(type(a))

<class 'str'>


In [3]:
c=int(a)
print(type(c))

<class 'int'>


In [4]:
v="abc"
print(type(v))

<class 'str'>


In [5]:
c=int(v)
print(type(c))

ValueError: invalid literal for int() with base 10: 'abc'

In [6]:
a=23.4
c=int(a)
print(type(c))

<class 'int'>


In [7]:
b=-123
print(type(b))

<class 'int'>


In [9]:
a='35'
print(type(int(a)+5))

<class 'int'>


In [14]:
b='35'
print(b+'10') # conconated method

3510


# input to changed to float

In [16]:
a=float(input("entre the 1st no:"))
b=float(input("entre the 2nd no:"))
c=a+b-a*b
print(f"the result of two n:{c}")

entre the 1st no:50
entre the 2nd no:5
the result of two n:-195.0


In [17]:
a=float(input("entre the 1st no:"))
b=float(input("entre the 2nd no:"))
c=a+b-a-b+a*b
print(f"the result of two n:{c}")

entre the 1st no:20
entre the 2nd no:10
the result of two n:200.0


In [18]:
# 23.5= float
#"abhishek"=string
# 23.5= float
#'abhi'= string 
# "1234"=string int
# 345=integar
# False=boolean
#'23.5'=string float
#'-23.5'=string float

# data type 

In [19]:
a=23.5
print(int(a))

23


In [20]:
b=23.9
print(int(b))

23


In [21]:
c='23'
d=int(c)
print(d)

23


In [24]:
c='23.5'         # don't b  direct changed string to integar
d=float(c)        # first to changed string to float 
e=int(d)           # then you changed integar
print(e)
print(type(e))

23
<class 'int'>


In [25]:
a='23'
b=int(a)
print(type(b))

<class 'int'>


In [26]:
a='-23.5'
b=float(a)
c=int(b)
print(type(c))

<class 'int'>


In [27]:
a='-23'
b=int(a)
print(type(b))

<class 'int'>


# boolean to inteager 

In [29]:
a=False
b=int(a)
print(b)

0


In [30]:
a=True      # boolean to integar
b=int(a)
print(b)

1


In [31]:
# 23.5=int()-convert
#'23'=convert=int()
#'34.5'=convert=float()then int()
# false=int()=convert
#12=int()=convert
# 'abhishek'-con't be changed
#'-23'=int()-convert
# '-23.5'=flaot () then int()

In [33]:
a="-23.5"
c=float(a)
d=int(c)
print(type(d))

<class 'int'>


In [34]:
a=-23
print(type(a))

<class 'int'>


# change to string format

In [1]:
a=23
b=str(23)
print(b)
print(type(b))

23
<class 'str'>


In [2]:
a=23.5
b=str(a)
print(b)
print(type(b))

23.5
<class 'str'>


In [3]:
a=abhishek
b=str(a)
print(b)
print(type(b))

NameError: name 'abhishek' is not defined

In [9]:
lan=float(input("entre the no:"))
bre=float(input("entre the breath:"))
area=int(lan*bre)
print(f"the area {area} of this plot")

entre the no:12
entre the breath:23
the area 276 of this plot


# change to boolean() 

In [10]:
a="234"
print(bool(a))
print(type(a))

True
<class 'str'>


In [11]:
b=23.5
c=bool(b)
print(type(c))
print(c)

<class 'bool'>
True


In [15]:
b="abhishek"
c=bool(b)
print(bool(c))
print(type(c))

True
<class 'bool'>


In [16]:
a=0             # when value indicate=0 then result come False 
b=bool(a)
print(b)
print(type(b))

False
<class 'bool'>


In [17]:
a=0.0          # when value indicate=0.0 then result come False 
c=bool(a)
print(c)
print(type(c))

False
<class 'bool'>


In [18]:
b="23.5"
c=bool(b)
print(c)
print(type(c))

True
<class 'bool'>


In [19]:
a=23345
b=bool(a)
print(b)
print(type(b))

True
<class 'bool'>


In [20]:
a=-125.67
b=bool(a)
print(b)
print(type(b))

True
<class 'bool'>


In [21]:
d=-1234
j=bool(b)
print(j)
print(type(j))

True
<class 'bool'>


# practice question

 1-take side of a sequre from user and print area and parameter of it?

In [22]:
length=int(input("entre the the length:"))
breath=int(input("entre the breth :"))
area=length * breath
pari=length*4
print(f"the area is:{area} and parimeter:{pari}")

entre the the length:12
entre the breth :12
the area is:144 and parimeter:48


In [24]:
name=input("entre the name:")
roll=int(input("entre the roll no:"))
foi=input("entre the foi:")
print(f"my name is {name} my roll no is:{roll} and my foi is {foi}.")

entre the name:nikhil pal
entre the roll no:4577
entre the foi:playing game
my name is nikhil pal my roll no is:4577 and my foi is playing game.


write one line 

In [26]:
str1=input("entre the personal intrest:")
str2=input("entre the name:")
print(str1+str2)

entre the personal intrest:data 
entre the name:nikhil
data nikhil


# string ep 7

In [27]:
stg='i love nikhil and i am very special boy then i reliese a movie nAME IS LOVE YOU MORE tyhen my love she love loyutr blkloue ojnmfr lkuo'
print(stg)

i love nikhil and i am very special boy then i reliese a movie nAME IS LOVE YOU MORE tyhen my love she love loyutr blkloue ojnmfr lkuo


In [2]:
print("love is everything 'but' something")

love is everything 'but' something


In [4]:
print('love is temparey but "not" some')

love is temparey but "not" some


In [5]:
print("love is tempory but not 'one' is the true")

love is tempory but not 'one' is the true


# indexing

In [7]:
a="love is king"     #01234567891011 - indexing no right to left
print(a[6])          #love is king
                       

s


In [8]:
b="love is bliend"
print(b[6])

s


In [9]:
c="i love you"
print(c[5])

e


In [10]:
r="11223456787"
print(r[5])

4


In [11]:
a="123345465qbnndkdiyu"
print(a[6])

4


In [12]:
b="122345678"         #-(987654321)  - indexing for right to left 
print(b[-5])          # "122345678"

4


In [16]:
b="#$%^&123shgdgd"
print(b[5])

1


In [18]:
b="#$%^&123shgdgd"
print(b[-5])

h


In [22]:
d="1.2.3.4.6.7.8"
print(d[-1])

8


In [1]:
d="1.2.3.4.6.7.8.9.10"
print(d[-1])

0


In [1]:
a="abhishek kumar"
print(a[5])

h


In [2]:
print(a[-3])

m


# slicing ep8

In [20]:
a='my name is nikhil'
print(a[0:5])

my na


In [4]:
print(a[:5])

my na


In [22]:
print(a[0::])

my name is nikhil


In [23]:
print(a[:1:])

m


In [14]:
print(a[::])

my name is nikhil


In [15]:
print(a[0:12:2])

m aei 


In [25]:
a="1223456781346"
print(a[:4])

1223


In [26]:
print(a[0:12:3])

1361


In [27]:
print(a[-4:-2])

13


In [29]:
print(a[-8:-2:])

567813


In [33]:
print(a[-6:])

781346


In [37]:
print(a[:-2:])

12234567813


In [39]:
print(a[:-1])

122345678134


In [40]:
print(a[-5::2])

836


# string function len(),max(),lower(),upper(),swapcase()

In [1]:
a="abhishek"
print(len(a))

8


In [2]:
a='123345hujki'
print(len(a))

11


In [3]:
a="nikhil pal"
print(len(a))

10


In [4]:
a="nikhil pal @#$,."
print(len(a))

16


max method

In [5]:
a="1234567894"
print(max(a))

9


In [6]:
a="abhishek"
print(max(a))

s


In [1]:
c="-1-2-3-4-5-6-7-8"
print(max(c))

8


In [2]:
a="1234567894"
print(min(a))

1


In [3]:
a="abhishek"
print(min(a))

a


In [4]:
c="-1-2-3-4-5-6-7-8"
print(min(c))

-


swapcase method

In [6]:
a="NikHil PaL"
print(a.swapcase())

nIKhIL pAl


In [7]:
a="IloVEyOu"
print(a.swapcase())

iLOveYoU


# title method

In [8]:
x="python"
print(x.title())

Python


In [10]:
c="NIkhil pal"
print(c.title())

Nikhil Pal


In [11]:
x="nikhil IS very Good boy"
print(x.title())

Nikhil Is Very Good Boy


capitalize() method

In [12]:
b="nikhil is good boy"
print(b.capitalize())

Nikhil is good boy


In [1]:
c="python is very good language"
x=c[0:6].upper()+c[6:]
print(x)

PYTHON is very good language


In [8]:
s="nikhil is good and innocent boy".strip(" ")
x=s[0:18]+" "+s[-12:].upper().strip(" ")
print(x)

nikhil is good and INNOCENT BOY


# strip () method 

In [16]:
stg="         nikhil pal is very good man       "
print(stg)
print()
print(stg.strip())

         nikhil pal is very good man       

nikhil pal is very good man


# lstrip

In [17]:
stg="         nikhil pal is very good man       "
print(stg)
print()
print(stg.lstrip())

         nikhil pal is very good man       

nikhil pal is very good man       


# rstrip

In [18]:
stg="         nikhil pal is very good man       "
print(stg)
print()
print(stg.rstrip())

         nikhil pal is very good man       

         nikhil pal is very good man


# programe build

In [4]:
x=input("entre the no:")
y=input("entre the 2nd no:")
z=x[0:5].upper()+" "+ x[5:]
a=y[0:6].upper()+" "+y[6:]
print(f"the value of z:{z}")
print()
print(f"the value of y:{a}")
      

entre the no:my name is nikhil
entre the 2nd nopython is very
the value of z:MY NA me is nikhil

the value of y:PYTHON  is very


In [9]:
x=input("entre the no:")
y=input("entre the no:")
z=x[0:6].strip().swapcase()
y=x[0:6].strip().swapcase()
print(f"vale of z:{z}")
print()
print(f" value of y:{y}")

entre the no:nikhil pal
entre the no:nitesh pal
vale of z:NIKHIL

 value of y:NIKHIL


# replace()

In [1]:
stg="nikhil is good boy"
a=stg.replace('nikhil','Mukesh')
print(a)

Mukesh is good boy


In [20]:
stg="mukesh is good man"
s=stg.replace("mukesh","nikhil").upper()
d=s[0:6].lower()+" "+s.title()
print(s)
print(d)

NIKHIL IS GOOD MAN
nikhil Nikhil Is Good Man


In [23]:
j="i  love my india"
r=j.replace("india","wife").title()
print(r)

I  Love My Wife


In [25]:
r="i love my wife and my wife is so beautiful"
g=r.replace("wife","india").title()
print(g)

I Love My India And My India Is So Beautiful


In [2]:
tg=input("entre the string:")
st=input("entre the sentence:")
rep=input("what you want replace:")
a=tg.replace(st,rep)
print(f"the final string is:{a}")


entre the string:my name is nikhil
entre the sentence:nikhil
what you want replace:mukesh
the final string is:my name is mukesh


In [7]:
st=input("first string:")
rep=input("do you want the replace name:")
add=input("do you want add this:")
a=st.replace(rep,add)
print(f"final string is:{a}")

first string:everyoe is were fake mak
do you want the replace name:fake
do you want add this:real
final string is:everyoe is were real mak


# count()

In [8]:
stg="12345678987654323456"
a=stg.count("5")
print(a)

3


In [10]:
a="nikhil pal is good boy"
d=a.count("i")
print(d)

3


In [14]:
stg=input("entre the string name:")
st=input("do you want count string charactor:")
a=stg.count(st)
print(f"the charator of string:{st} comes in string:{a} times")

entre the string name:my ame is nikhil pal
do you want count string charactor:nikhil
the charator of string:nikhil comes in string:1 times


In [3]:
n="12345678123456"
b=n.count("1")
print(b)

2


In [4]:
b="nikhil is good boy"
c=b.count("n")
print(c)

1


In [5]:
c="nikhil loves deeksha"
v=c.count("k")
print(v)

2


In [7]:
z="love is bliend"
c=z.count("l")
print(c)

2


In [8]:
c="black adam is good boy"
b=c.count("b")
print(b)

2


# find( method)

In [19]:
c="i love is deeksha"
f=c.find("deeksha")
print(f)

10


In [18]:
b="121345678"
g=b.find("8")
print(g)

8


In [39]:
c="i love nikhil but i love nikhil"
g=c.find("i",8)
print(g)

8


In [41]:
c="i love nikhil but i love nikhil or nikhil"
fi=c.find("nikhil")
si=c.find("nikhil",fi+1)
ti=c.find("nikhil",si+1)
print(fi,si,ti)

7 25 35


In [1]:
c=input("entre the name:")
fv=input("entre the name do you want find:")
v=c.find(fv)
print(f"the value you want find:{fv} and postion no is:{v}")

entre the name:my name is nikhil and nikhil pal
entre the name do you want find:nikhil
the value you want find:nikhil and postion no is:11


rfind- right to left find

In [3]:
stg="i love nikhil but nikhil love mobile"
f=stg.find("mobile")
print(f)
print()
f1=stg.rfind("nikhil")
print(f1)

30

18


In [10]:
f="123456789"
f1=f.rfind("9")
print(f1)


8


# index()

In [11]:
s="i love you"
z=s.index("y")
print(z)

7


In [12]:
c="122345678910"
f=c.index("8")
print(f)

8


rindex()-right to left indexing

In [14]:
c="1234567"
f=c.rindex('5')
print(f)

4


In [15]:
s="i love you"
z=s.rindex("y")
print(z)

7


In [19]:
s="i love python"
a=s.find("java")
print(a)
print()
c=s.rindex("python")
print(c)

-1

7


# string split() method

In [17]:
s="this is nikhil"
d=s.split(" ")
print(d)

['this', 'is', 'nikhil']


In [24]:
s="ilovenikhil"
c=s.split(' ')
print(c)

['ilovenikhil']


In [25]:
a="123456789"
x=a.split(" ")
print(x)

['123456789']


In [33]:
s='abhi;nikhil;ram;nisha'
a=s.split(";")
print(a)

['abhi', 'nikhil', 'ram', 'nisha']


max split()

In [34]:
s='abhi;nikhil;ram;nisha;rahul;nishant'
c=s.split(";",3)
print(c)

['abhi', 'nikhil', 'ram', 'nisha;rahul;nishant']


In [35]:
b="i love nikhil pal but i am not robot"
x=b.split(" ",4)
print(x)

['i', 'love', 'nikhil', 'pal', 'but i am not robot']


In [37]:
s='abhi;nikhil;ram;nisha;rahul;nishant'
a=s.split(";",5)
print(a)

['abhi', 'nikhil', 'ram', 'nisha', 'rahul', 'nishant']


In [38]:
#write a programe
a='abhi&nikhil&ram&nisha&rahul&nishant'
c=a.split("&")
print(c)
b="i@love@nikhil@pal@but@i@am@not@robot"
v=b.split("@")
print(v)

['abhi', 'nikhil', 'ram', 'nisha', 'rahul', 'nishant']
['i', 'love', 'nikhil', 'pal', 'but', 'i', 'am', 'not', 'robot']


In [44]:
a='abhi&#$nikhil&#$ram&#$nisha&#$rahul&#$nishant'
b=str(input('entre the symbol do you want delete the string:'))
c=a.split(b)
print(f"the delete of symbol:{b} the final list:{c}")

entre the symbol do you want delete the string:&#$
the delete of symbol:&#$ the final list:['abhi', 'nikhil', 'ram', 'nisha', 'rahul', 'nishant']


In [45]:
x="1*2*3*456789"
s=x.split("*",3)
print(s)

['1', '2', '3', '456789']


# partition()

In [46]:
a='abhi&#$nikhil&#$ram&#$nisha&#$rahul&#$nishant'
c=a.partition(" ")
print(c)

('abhi&#$nikhil&#$ram&#$nisha&#$rahul&#$nishant', '', '')


In [53]:
a='this is python no love'
s=a.partition(" ")
print(s)

('this', ' ', 'is python no love')


In [54]:
b="i@love@nikhil@pal@but@i@am@not@robot"
c=b.partition("@")
print(c)

('i', '@', 'love@nikhil@pal@but@i@am@not@robot')


# rpartition

# islower() method

In [55]:
s='sandeep'
c=s.islower()
print(c)

True


In [56]:
v="nikhil1234"
c=v.islower()
print(c)

True


In [57]:
n="NIKhil"
c=n.islower()
print(c)

False


# isupper() method

In [59]:
stg="NIUKHIL"
s=stg.isupper()
print(s)

True


In [61]:
s="NIKHIL!@#2345"
c=s.isupper()
print(c)

True


In [62]:
s="nikhil"
v=s.isupper()
print(v)

False


# isalpha()method

In [63]:
c="nikhilpaldskUYYTTRF"
s=c.isalpha()
print(s)

True


In [64]:
v="abnhklETYUUH123"
s=v.isalpha()
print(s)

False


# isalnum()method

In [65]:
x="love12"
c=x.isalnum()
print(c)


True


In [66]:
x="1234"
c=x.isalnum()
print(c)

True


In [67]:
b="wRYUbgjm"
k=b.isalnum()
print(k)

True


In [68]:
c="#$%^ashjk123"
b=c.isalnum()
print(b)

False


# startswith()method

In [70]:
s="abhishek"
c=s.startswith("abhi")
print(c)

True


In [71]:
a="nikhil"
c=a.startswith("nikl")
print(c)

False


# endswith()

In [72]:
s="nikhil pal"
v=s.endswith("al")
print(v)

True


In [73]:
c="sanddep singh"
c=c.endswith("ghj")
print(c)

False


# membership operator- in,not in

In [4]:
d='this is python'
c="python not string"
print(  c in d )

False


In [6]:
s="my name is nikhil"
d="nikhil"
print( d in s)

True


In [7]:
d="nikhil love python"
s="love"
print(s in d)

True


In [9]:
stg="hello this is python i am nikhil"
f=input("entre the name do you want find:")
print(f in stg)

entre the name do you want find:nikhil
True


In [11]:
v="1234567890"
b="9"
print(b not in v)

False


In [12]:
c="1234567"
b="9"
print(b not in c)

True


In [14]:
b="i love in so much"
c="nikhil"
print( c not in b)

True


# condistional statement-if,else,elif,

In [17]:
stg=input("entre the string:")
if(stg.upper()):
    print(stg.upper())

entre the string:nikhil
NIKHIL


In [20]:












v=input("entre the string")
if(v.lower()):
    print(v.lower())

entre the stringNIKHIL PAL IS GOOD BOY
nikhil pal is good boy


In [24]:
c=input("entre the string:")
if(c.swapcase()):
    print(c.swapcase())


entre the string:NiKHil LoVE PytHOn
nIkhIL lOve pYThoN


In [25]:
b=input("entre the string:")
if(b.title()):
    print(b.title())
    

entre the string:NIKhil pal IS
Nikhil Pal Is


In [28]:
b="nikhil love dog"
v=input("entre the name do you want replace:")
c=input("do you want add this:")
if(b.replace(v,c)):
    print(b.replace(v,c))


entre the name do you want replace:dog
do you want add this:cat
nikhil love cat


# find odd and even

In [5]:
num=int(input("entre the value:"))
if(num%2==0):
    print("even number")
else:
    print("odd number")
print("have a good day")

entre the value:2
even number
have a good day


# find area of area

In [2]:
length=int(input("entre the of the area lenght:"))
breath=int(input("entre the of the area of breath:"))
if(length==breath):
    print("sequre")
else:
    print("rectangle")


entre the of the area lenght:12
entre the of the area of breath:13
rectangle


In [3]:
sal=int(input("entre the salary:"))
exp=int(input("entre the experience:"))
if(exp>5):
    bonus=sal*10/100
else:
    bonus=0
print(f"your Bonus:{bonus}")
print(f"salary this month:{sal+bonus}")
print("have a good day")

entre the salary:50000
entre the experience:6
your Bonus:5000.0
salary this month:55000.0
have a good day


In [16]:
num=int(input("entre the name:"))
if(num>5 and num<10 ):
    print("i love you nikhil")
else:
    print("i hate you")

entre the name:11
i hate you


In [23]:
quantity=int(input("how many pens did you buy:"))
copq=quantity *10
if(copq>1000):
    discount=copq*10/100
else:
    discount=0
print(f"discount:{discount}")
print(f"total bill:{copq-discount}")

how many pens did you buy:101
discount:101.0
total bill:909.0


In [1]:
marks=int(input("entre your marks:"))
if(marks>=80):
    print("you got A Grade")
elif(marks>=60 and marks < 80):
    print("you got B Grade")
elif(marks>=50 and marks < 60):
    print("you got C grade")
elif (marks>=40 and marks <50):
    print("you got D grade")
elif(marks>=25 and marks<40):
    print("you got E grade")
else:
    print("you fail")


entre your marks:56
you got C grade


In [10]:
ott=input("what do you have:")
if(ott=="netflix"):
    print("watch black adam")
elif(ott=="amazon"):
    print("watch the family man")
elif(ott=="sonytv"):
    print("watch scam 1992")
else:
    print("watch doordarshan")
print("keep watching")

what do you have:amazon
watch the family man
keep watching


In [18]:
marks=int(input("entre the number:"))
if(marks>=80):
    print("topper")
elif(marks>=60 and marks<80):
    print("very good")
elif(marks>=40 and marks<60):
    print("good")
else:
    print("fail")
print("keep learing")

entre the number:76
very good
keep learing


In [25]:
mall_open=input("is mall open?")
if(mall_open=="yes"):
    big_b=input("is big bazar open?")
    if(big_b=="yes"):
        plays=input("is playstation availbale")
        if(plays=="yes"):
            discount=input("is there any discount")
            if(discount=="yes"):
                print("buy it")


is mall open?yes
is big bazar open?yes
is playstation availbaleyes
is there any discountyes
buy it


In [32]:
s_id=input("create your user id:").lower()
s_pd=input("ceate your user password:")
l_id=input("entre your user id:").lower()
l_pd=input("entre your user password:")
if(s_id==l_id and s_pd==l_pd):
    print("login sucessfully welcome")
else:
    print("login failed please try again")

create your user id:NIKhil
ceate your user password:12345
entre your user id:nikHIL
entre your user password:12345
login sucessfully welcome


In [41]:
s_id=input("create your user id:").lower()
s_pd=input("ceate your user password:")
l_id=input("entre your user id:").lower()
l_pd=input("entre your user password:")
if(s_id==l_id and s_pd==l_pd):
    print("login sucessfully welcome")
elif(s_id!= l_id ):
    print("lnvaild id")
    print("login failed please try again")
elif(s_pd!=l_pd):
    print("invaild password")
    print("login failed please try again")


create your user id:nikhil
ceate your user password:12345
entre your user id:nikhil
entre your user password:12345
login sucessfully welcome


# LOOP while and for 

In [3]:
#1 to 100 no print
i=1
while(i<=10):
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10


In [1]:
i=1
while(i<=5):
    print("spider man watch")
    i+=1

spider man watch
spider man watch
spider man watch
spider man watch
spider man watch


In [3]:
i=1
while(i<=10):
    print("hulk movie watch")
    i+=1

hulk movie watch
hulk movie watch
hulk movie watch
hulk movie watch
hulk movie watch
hulk movie watch
hulk movie watch
hulk movie watch
hulk movie watch
hulk movie watch


table print

In [4]:
i=1
num=5
while(i<=10):
    print(num*i)
    i+=1

5
10
15
20
25
30
35
40
45
50


In [6]:
num=int(input("entre the no:"))
i=1
while(i<=70):
    print(f"{num}*{i}={num*i}")
    i+=1

entre the no:7
7*1=7
7*2=14
7*3=21
7*4=28
7*5=35
7*6=42
7*7=49
7*8=56
7*9=63
7*10=70
7*11=77
7*12=84
7*13=91
7*14=98
7*15=105
7*16=112
7*17=119
7*18=126
7*19=133
7*20=140
7*21=147
7*22=154
7*23=161
7*24=168
7*25=175
7*26=182
7*27=189
7*28=196
7*29=203
7*30=210
7*31=217
7*32=224
7*33=231
7*34=238
7*35=245
7*36=252
7*37=259
7*38=266
7*39=273
7*40=280
7*41=287
7*42=294
7*43=301
7*44=308
7*45=315
7*46=322
7*47=329
7*48=336
7*49=343
7*50=350
7*51=357
7*52=364
7*53=371
7*54=378
7*55=385
7*56=392
7*57=399
7*58=406
7*59=413
7*60=420
7*61=427
7*62=434
7*63=441
7*64=448
7*65=455
7*66=462
7*67=469
7*68=476
7*69=483
7*70=490


take 10 value in input in

In [1]:
i=1
while(i<=10):
    x=int(input("entre the number"))
    i+=1

entre the number12
entre the number2
entre the number3
entre the number3
entre the number4
entre the number5
entre the number6
entre the number7
entre the number87
entre the number9


# sum

In [6]:
bank=0
i=1
while(i<=3):
    money=int(input("how much money you to deposite:"))
    bank=bank+money
    i+=1 
    print("total money:{bank}"
          

trans=0
i=1          
while(i<=2):
    tranzition=int(input("tansition money:"))
    trans=bank-tranzition
    
print(f"total money in bank:{trans}")

SyntaxError: invalid syntax (2184371298.py, line 10)

In [7]:
i=1
s=0
numbers=int(input("how many numbers do you want:"))
while(i<=numbers):
    x=int(input("entre the numbers:"))
    s=s+x
    i+=1
print(f"sum of all numbers:{s}")




























print(f"averge:{s/numbers}")

how many numbers do you want:3
entre the numbers:1
entre the numbers:2
entre the numbers:3
sum of all numbers:6
averge:2.0


# even no print

In [2]:
i=1
while(i<=100):
    print(i)
    i+=2

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99


# ep13

In [6]:
i=1
s=0
while(i<=10):
    var=int(input("entre the number:"))
    s+=var
    i+=1
print(f"total of digit:{s}")

entre the number:12
entre the number:3
entre the number:4
entre the number:5
entre the number:6
entre the number:7
entre the number:8
entre the number:9
entre the number:1
entre the number:2
total of digit:57


In [16]:
i=1
s=1
while(i<=5):
    var=int(input("entre the number:"))
    s=s*var
    v=s*i
    i+=1
print(f"multiply of total number:{v}")

entre the number:12
entre the number:23
entre the number:4
entre the number:5
entre the number:6
multiply of total number:165600


In [23]:
i=1
s=1
while(i<=3):
    var=int(input("entre the value:"))
    s=s*var
    c=s+var
    i+=1
print(f"total multiply of sum:{s}")

entre the value:1
entre the value:2
entre the value:3
total multiply of sum:6


In [24]:
s=0
while(in loop):
    var=int(input("entre the number"))
    s=s+var
    quit=input("do you want to quit??")
    if(quit=="y"):
        inloop="braks'

SyntaxError: invalid syntax (2327596422.py, line 2)

# break statement

In [27]:
i=1
while(i<=3):
    var=int(input("entre the no:"))
    if(var<10):
        break
    i+=1
else:
    print("you are in priented 3 values:")

entre the no:11
entre the no:12
entre the no:13
you are in priented 3 values:


# guess the number programe

In [1]:
import random
chance=1
while(chance<=10):
    a=random.randint(1,100)
    print(f"original number:{a}")
    guess_number=int(input("entre the no:"))
    if(guess_number==a):
        print("you won")
        break
    elif(guess_number>a):
        print("hint:choose a lower number")
    else:
        print("hint:choose a higher a number")
    print(f"------------------------------you have:{10-chance}:chance left----------------------")
    chance=chance+1
else:
    print(f"sorry you don't get number try again later")

original number:2
entre the no:2
you won


# ep14 for loop in python

In [4]:
d=[1,2,3,4,5,6]
for i in d:
    print(i)

1
2
3
4
5
6


In [5]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [6]:
for i in range(1,21,2):
    print(i)

1
3
5
7
9
11
13
15
17
19


In [10]:
raj=[1,2,3,4]
for i in raj:
    print('abhi')

abhi
abhi
abhi
abhi


In [11]:
for i in range(1,11,1):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [12]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [13]:
for i in range(11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [15]:
for i in range(1,11,2):
    print(i*5)

5
15
25
35
45


In [16]:
for i in "nikhil":
    print(i)

n
i
k
h
i
l


In [20]:
for i in "sankar":
    print(i)

s
a
n
k
a
r


In [23]:
for i in "rahulk":
    print(i)

r
a
h
u
l
k


In [25]:
for i in "neeraj":
    print(i)

n
e
e
r
a
j


In [26]:
num=int(input("entre the no:"))
for i in range(num,num*10+1,num):
    print(i)

entre the no3
3
6
9
12
15
18
21
24
27
30


In [27]:
num=int(input("entre the no:"))
for i in range(num,num*10+1,num):
    print(i)

entre the no:22
22
44
66
88
110
132
154
176
198
220


In [30]:
num=int(input('entre the value:'))
for i in range(num,num*10+1,num):
    print(i)

entre the value:134
134
268
402
536
670
804
938
1072
1206
1340


In [34]:
one=["raj","rahul","rakesh","raj"]
for i in one :
    print("abhi")

abhi
abhi
abhi
abhi


In [36]:
r='nikhil pal'
for i in 'nikhil pal':
    print(i)

n
i
k
h
i
l
 
p
a
l


In [37]:
g=['qwtre','123','45778','-457','78.90','False','0']
for i in g:
    print("nikhil pal")

nikhil pal
nikhil pal
nikhil pal
nikhil pal
nikhil pal
nikhil pal
nikhil pal


# ep 15 list

In [5]:
a=['nikhil','3724','28','parmanent'] #any type of data you can store in list allow duplicate vailue and result comes in list
print(type(emp_detils))

<class 'list'>


In [6]:
print(a[2])

28


In [7]:
print(a[1])

3724


# slicing

In [9]:
a=['nikhil','3724','28','parmanent','balaji','green shirt','sitargunj']
f=a[0:3]
print(f)

['nikhil', '3724', '28']


In [10]:
d=a[1::]
print(d)

['3724', '28', 'parmanent', 'balaji', 'green shirt', 'sitargunj']


In [11]:
s=a[:7:]
print(s)

['nikhil', '3724', '28', 'parmanent', 'balaji', 'green shirt', 'sitargunj']


In [12]:
c=a[::2]
print(c)

['nikhil', '28', 'balaji', 'sitargunj']


mutable data type/ changeble data type

In [14]:
d=24
print(id(d))
d=25
print(id(d))

1337968454672
1337968454704


new value replace in list

In [15]:
a=['nikhil','3724','28','parmanent','balaji','green shirt','sitargunj']
a[1]="ram"
print(a)

['nikhil', 'ram', '28', 'parmanent', 'balaji', 'green shirt', 'sitargunj']


In [16]:
a=['nikhil', 'ram', '28', 'parmanent', 'balaji', 'green shirt', 'sitargunj']
a[4]="love"
print(a)

['nikhil', 'ram', '28', 'parmanent', 'love', 'green shirt', 'sitargunj']


In [19]:
a=['nikhil', 'ram', '28', 'parmanent', 'balaji', 'green shirt', 'sitargunj']
x=len(a)
print(x)

7


In [22]:
a=['nikhil', 'ram', '28', 'parmanent', 'balaji', 'green shirt', 'sitargunj',"-12","-1","False","-12.4"]
x=max(a)
print(x)

sitargunj


In [23]:
a=['nikhil', 'ram', '28', 'parmanent', 'balaji', 'green shirt', 'sitargunj',"-12","-1","False","-12.4"]
x=min(a)
print(x)

-1


In [24]:
# concate of two list 
home=["family","dog","bike"]
office=["work","tension","sellery"]
l=home+office
print(l)

['family', 'dog', 'bike', 'work', 'tension', 'sellery']


In [25]:
#concate of  3 list
name=["nikhil","ram","rakesh"]
game=["cricket","football","vollyboll"]
city=["delhi","kanpur","lucknow"]
x=name+game+city
print(x)

['nikhil', 'ram', 'rakesh', 'cricket', 'football', 'vollyboll', 'delhi', 'kanpur', 'lucknow']


# work in for loop

In [26]:
for i in [1,2,3,4,5,6]:
    print(i)


1
2
3
4
5
6


add the value in list-append function.append add a value at the end of the list.

In [27]:
a=['nikhil', 'ram', '28', 'parmanent', 'balaji', 'green shirt', 'sitargunj']
a.append("23")
print(a)


['nikhil', 'ram', '28', 'parmanent', 'balaji', 'green shirt', 'sitargunj', '23']


In [28]:
a=['nikhil', 'ram', '28', 'parmanent', 'balaji', 'green shirt', 'sitargunj', '23']
a.append("12","13")
print(a)

TypeError: list.append() takes exactly one argument (2 given)

In [29]:
a=['nikhil', 'ram', '28', 'parmanent', 'balaji', 'green shirt', 'sitargunj', '23']
a.append("rose"["a","d"])
print(a)

<>:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\nikhil pal\AppData\Local\Temp\ipykernel_13896\971400624.py:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  a.append("rose"["a","d"])
C:\Users\nikhil pal\AppData\Local\Temp\ipykernel_13896\971400624.py:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  a.append("rose"["a","d"])
C:\Users\nikhil pal\AppData\Local\Temp\ipykernel_13896\971400624.py:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  a.append("rose"["a","d"])


TypeError: string indices must be integers

In [30]:
s=[]
v=input("entre the value:")
s.append(v)
print(s)

entre the value:ram
['ram']


In [31]:
c=[]
d=int(input("rntre the value"))
c.append(d)
print(c)

rntre the value12345566677
[12345566677]


In [32]:
e=[]
d=input("entre the value:")
e.append(d)
print(e)

entre the value:nikhil pal
['nikhil pal']


In [33]:
g=[]
f=int(input("entre the no:"))
g.append(f)
print(g)

entre the no:8477900199
[8477900199]


In [1]:
g=[]
l=input("entre the name:")
g.append(l)
print(g)

entre the name:nikhil love deeksha
['nikhil love deeksha']


input value the integer or alphabatic

In [6]:
l=[]
for i in range(5):
    value=input("entre the value:")
    if(value. isnumeric()):
        l.append(int(value))
    else:
        l.append(value)
        

print(f"final list:{l}")

entre the value:123
entre the value:456
entre the value:6787
entre the value:nikhil
entre the value:raaj
final list:[123, 456, 6787, 'nikhil', 'raaj']


# extend function()

In [7]:
l=["noida",'delhi','noida']
l.append(['pune','delhi','noida'])
print(l)


['noida', 'delhi', 'noida', ['pune', 'delhi', 'noida']]


In [8]:
l=["noida",'delhi','noida']
l.extend(['pune','delhi','noida'])
print(l)

['noida', 'delhi', 'noida', 'pune', 'delhi', 'noida']


In [9]:
l=["nikhil","balaji","3724"]
l.extend(["love",'sex','wax'])
print(l)

['nikhil', 'balaji', '3724', 'love', 'sex', 'wax']


insert() method

In [10]:
l=['nikhil','python','670']
l.insert(2,"love")
print(l)

['nikhil', 'python', 'love', '670']


In [11]:
z=['love','sex'<"1234","girl","-90"]
z.insert(3,"bus")
print(z)

['love', False, 'girl', 'bus', '-90']


In [12]:
v=['kilo','has','hi','v']
v.insert(2,"nikhil")
print(v)

['kilo', 'has', 'nikhil', 'hi', 'v']


remove()method

In [13]:
l=["love","sex",'girl']
l.remove("girl")
print(l)

['love', 'sex']


In [14]:
o=["love","girl","rose","gun"]
o.remove("rose")
print(o)

['love', 'girl', 'gun']


remove programe

In [20]:
o=["love","girl","rose","gun"]
for i in range(3):
    value=input("entre the value:")
    o.remove(value)
print(f"final list:{o}")

entre the value:love
entre the value:rose
entre the value:girl
final list:['gun']


In [21]:
emp=["1213","wer","nikhil","ghi"]
if("nikhil"in emp):
    print("yes")
else:
    print("no")

yes


In [22]:
emp=["1213","wer","nikhil","ghi","rakesh"]
if("nikhil" in emp):
    emp.remove("nikhil")
print(emp)

['1213', 'wer', 'ghi', 'rakesh']


In [23]:
emp=["1213","wer","nikhil","ghi","rakesh","pandit","12"]
if("12" in emp):
    emp.remove('12')
print(emp)

['1213', 'wer', 'nikhil', 'ghi', 'rakesh', 'pandit']


# pop()method

In [3]:
emo=["123","nikhil","rahul"]
emo.pop(1)
print(emo)

['123', 'rahul']


In [4]:
company=["nikhil",'balaji','3724','yes']
g=company.pop(2)
print(company)
print(g)

['nikhil', 'balaji', 'yes']
3724


In [10]:
emp=["1213","wer","nikhil","ghi","rakesh","pandit","12"]
k=emp.pop(3)
print(emp)
print(k)

['1213', 'wer', 'nikhil', 'rakesh', 'pandit', '12']
ghi


# function type 

In [12]:
emp='nikhil'             # this type is function is return type  fuction
x=emp.replace('i','k')
print(x)

nkkhkl


In [13]:
emp=["nikhil","rahul","suresh"]       ## this type is function is not return type  fuction
emp.append("abhishek")
print(emp)

['nikhil', 'rahul', 'suresh', 'abhishek']


clear method()

In [16]:
l=["nikhil","mukesh","123","-23"]
l.clear()
print(l)

[]


In [17]:
l=["123","nikhill","rahul","123234"]
l.clear()
print(l)

[]


copy( method)

In [21]:
a=5
b=6
print(id(a),id(b))


2023895689648 2023895689680


In [22]:
a=5
b=a
print(id(a),id(b))

2023895689648 2023895689648


In [28]:
a=[1,2,3]
b=a
print(a,b)
a.append(4)
print(a,b)
print(id(a),id(b))

[1, 2, 3] [1, 2, 3]
[1, 2, 3, 4] [1, 2, 3, 4]
2024011211968 2024011211968


list reference

In [32]:
a=[1,2,3,4]
b=a.copy()
print(a,b)
a.append(5)
print(a,b)
print(id(a),id(b))

[1, 2, 3, 4] [1, 2, 3, 4]
[1, 2, 3, 4, 5] [1, 2, 3, 4]
2024010835584 2024010801408


reverse method

In [35]:
a=[1,2,3,4,5,567,456,60,40] #asending order
a.sort()
print(a)

[1, 2, 3, 4, 5, 40, 60, 456, 567]


In [37]:
s=[1,2,3,4,5,6,7,8,9,3,4,5,6,7,8,91,2,50,55,66,30]
s.sort()
print(s)

[1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 30, 50, 55, 66, 91]


In [38]:
a=[1,2,3,4,5,6,7,8,9,3,4,5,6,7,8,91,2,50,55,66,30] #descending order
a.sort(reverse=True)
print(a)

[91, 66, 55, 50, 30, 9, 8, 8, 7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 2, 2, 1]


In [39]:
b=[90,50,45,100,109,200,566,333,456,678,456,7,8,8,90,566]
b.sort(reverse=True)
print(b)

[678, 566, 566, 456, 456, 333, 200, 109, 100, 90, 90, 50, 45, 8, 8, 7]


del() method

In [47]:
a=[1,2,3,4,5,6,78,1233,5,6,7,889]
print(max(a))
del(a)
print(a)

1233


NameError: name 'a' is not defined

In [46]:
a

NameError: name 'a' is not defined

# take 10 integer and print then list

In [1]:
a=[]
for i in range(5):
    var=int(input("entre the no:"))
    a.append(var)
print(a)

entre the no:12
entre the no:3
entre the no:34
entre the no:5
entre the no:67
[12, 3, 34, 5, 67]


In [2]:
a=[]
for i in range(5):
    var=input("entre the sentence:")
    a.append(var)
print(a)

entre the sentence:nikhil
entre the sentence:love
entre the sentence:himself
entre the sentence:by world
entre the sentence:in this
['nikhil', 'love', 'himself', 'by world', 'in this']


count() function

In [3]:
ny=[1,2,3,4,5,6,6,6,7,7,8,9,19]
ny.count(6)

3

In [5]:
ny=[1,2,3,4,5,6,6,6,7,7,8,8,8,8,8,9,19]
s=ny.count(9)
print(s)

1


# index () function

In [6]:
ny=[1,2,3,4,5,6,6,6,7,7,"abhi",8,8,8,8,8,9,19]
ny.index("abhi")



10

In [7]:
ny=[1,2,3,4,5,6,6,6,7,7,"abhi",8,8,8,8,8,9,19]
x=ny.index(19)
print(x)

17


In [13]:
x=[12,222,30,11,33,19,-12,-23,-34,56.56,55.78]
even_list=[]
odd_list=[]
pos_list=[]
neg_list=[]
for x in numers:
    if (x%2==0):
        even_list.append(x)
    else:
        odd_list.append(x)
    if(x<0):
         pos_list.append(x)
    else:
         neg_list.append(x)

NameError: name 'numers' is not defined

tuple ()

In [8]:
name=('nikhil',"ram","mohit",12,"mohit")
print(name)
print(type(name))

('nikhil', 'ram', 'mohit', 12, 'mohit')
<class 'tuple'>


In [4]:
name[0:3]

('nikhil', 'ram', 'mohit')

In [5]:
name[:4]

('nikhil', 'ram', 'mohit', 12)

In [6]:
name[0:]

('nikhil', 'ram', 'mohit', 12)

In [7]:
name[::2]

('nikhil', 'mohit')

two tuple add them

In [11]:
for i in name:
    print(i)
    name.count("mohit")

nikhil
ram
mohit
12
mohit


In [13]:
names=(4,5)+(6,7)
print(type(names))

<class 'tuple'>


In [16]:
name=(4)+(6)
print(name)
print(type(name))

10
<class 'int'>


In [17]:
name=(4,)+(6,)
print(name)

(4, 6)


In [18]:
print(type(name))

<class 'tuple'>


# dict()

In [19]:
emp={"name":"nikhil","emp_code":"3724"}


In [20]:
emp["name"]="mohit"

In [21]:
emp

{'name': 'mohit', 'emp_code': '3724'}

In [24]:
n=emp["name"]
if(n=='mohit'):
    print("welcome")
else:
    print("not welcome")

welcome


In [4]:
emp_detils={
    "name":["nikhil",'mohit','mukesh',"rahul"],
    "company":['genpact','lg','cyinet','maq'],
    "leave":[10,12,17,20],
}
empolyee=input("entre the empolyee name")
empolyees= emp_detils['name']
if(empolyee in empolyees):
    print("present in our data")
else:
    print("not is our data")

entre the empolyee namenikhil
present in our data


In [4]:
emp_detils={
    "name":["nikhil",'mohit','mukesh',"rahul"],
    "company":['genpact','lg','cyinet','maq'],
    "leave":[10,12,17,20],
}
empolyee=input("entre the empolyee name:")
empolyees= emp_detils['name']
companies=emp_detils['company']
leaves=emp_detils["leave"]
if(empolyee in empolyees):
    pos=empolyees.index(empolyee)
    company=companies[pos]
    leave=leaves[pos]
    print(f"Employee company name:{company} Balance leave:{leave}")
else:
    print("not in our data")

entre the empolyee name:rahul
Employee company name:maq Balance leave:20


# tuple to list()

In [10]:
t=(1,2,3)
x=list(t)
print(type(x))

<class 'list'>


In [12]:
t=(1,2,3,4,5,6)
l=list(t)
t=tuple(l)
print(t)

(1, 2, 3, 4, 5, 6)


In [5]:
emp_detils={
    "name":["nikhil",'mohit','mukesh',"rahul"],
    "company":['genpact','lg','cyinet','maq'],
    "leave":[10,12,17,20],
} 

print(list(emp_detils.keys()))

['name', 'company', 'leave']


# dict some method

In [26]:
d={
    "name":"raj",
    "company":"genpact",
    "leave": 10
}

In [27]:
d["name"]="nikhil"
print(d)

{'name': 'nikhil', 'company': 'genpact', 'leave': 10}


In [18]:
k=d.keys()
print(k)

dict_keys(['name'])


In [6]:
print(d.values())

dict_values(['nikhil', 'genpact', 10])


# making dict to help of user input

In [ ]:
d={}
for i in range(3):
    k=input("entre the key:")
    v=input("entre the value:")
    d[k]=v
    print(d)

In [6]:
d={
    "name":"nikhil",
    "company":"balaji",
    "roll":"paramrnt",
    "city":"sitargunj",
    "pin_no":262543
}






In [16]:
print(d)

{}


In [3]:
d.pop("name")
print(d)

{'company': 'balaji', 'roll': 'paramrnt'}


In [4]:
v=d.pop("roll")
d["roll_no"]=v
print(d)

{'company': 'balaji', 'roll_no': 'paramrnt'}


In [5]:
d["company name"]=d.pop("company")
print(d)

{'roll_no': 'paramrnt', 'company name': 'balaji'}


In [15]:
print(d) 

{}


In [9]:
d["pin_code_no"]=d.pop("pin_no")
print(d)

{'name': 'nikhil', 'company': 'balaji', 'roll': 'paramrnt', 'city': 'sitargunj', 'pin_code_no': 262543}


pop item

In [11]:
print(d.popitem())

('pin_code_no', 262543)


In [12]:
print(d)

{'name': 'nikhil', 'company': 'balaji', 'roll': 'paramrnt', 'city': 'sitargunj'}


clear()

In [13]:
print(d.clear())

None


In [14]:
print(d)

{}


In [21]:
print(d)

{'name': 'nikhil', 'company': 'genpact', 'leave': 10}


In [29]:
r=d.copy()
print(r)

{'name': 'nikhil', 'company': 'genpact', 'leave': 10}


In [30]:
print(d.clear())

None


In [31]:
print(d)

{}


In [32]:
print(r)

{'name': 'nikhil', 'company': 'genpact', 'leave': 10}


# function()

In [37]:
def devendra():           #build function
    print('go away')
def nikhil ():
    print("do it now")

In [35]:
devendra ()                  # calling function   #user defined fuction

go away


In [38]:
nikhil()         #calling fucntion   #user defined fuction

do it now


In [44]:

def nikhil(food):
    print(f"i serve {food}" )     #that is parameter

In [42]:
nikhil("chowin")          # that is arugment

i serve chowin


In [6]:
def cal(sum):
    t=sum*10
    print(t)

In [7]:
cal(456)

4560


In [8]:
cal(20)

200


In [22]:
import userdefination as us
call(90)

900


In [3]:
import import_ipynb
import my_mod
from my_mod import *
add(5,5)

130


In [1]:
import import_ipynb
import plan
from plan import *
result(5,6,7)

importing Jupyter notebook from plan.ipynb
-8


In [2]:
result(2,4,5)

-7


# return type function

In [12]:
import import_ipynb
import xxx
from xxx import *
c=vote(17)
if(c==True):
    print('you can vote')
else:
    print("you can't vote")

you can't vote


# making sum type function

In [5]:
import import_ipynb
import xxx
from xxx import *
x=[1,2,3,4,5,'abhi',6,'nikhil',7]
s=sum(x)
print(f"the value sum is:{s}")


the value sum is:28


In [6]:
import import_ipynb
import xxx
from xxx import *
print(adds(3,5))
calc(10,5)
y=calc(10,5)
print(f"value of no:{y}")
type(y)

8
value of no:(15, 5, 50, 2.0)


tuple

In [1]:
import import_ipynb
import xxx
from xxx import *
add,sub,mul,div=cal(10,5)
print(add)
print(sub)
print(mul)
print(div)

importing Jupyter notebook from xxx.ipynb
15
5
15
2.0


In [2]:
import import_ipynb
import xxx
from xxx import *
s=nik(4)
print(s)

4


# making fraction to find factor

In [6]:
import import_ipynb
import factor
from factor import *
s=fact(6)
print(f"factor of numbers:{s}")

1
2
3
4
5
factor of numbers:None


# find perfect no

In [10]:
import import_ipynb
import factor
from factor import *
check=perfect(6)
if check==:
    print("its is perfect no")
else:
    print("not perfect")

SyntaxError: invalid syntax (2345499871.py, line 5)

In [3]:
import import_ipynb
import factor
from factor import *
num=int(input("entre the no:"))
s=fact(num)
print(f"the factor of given no {s}")
import import_ipynb
import factor
from factor import *
n=int(input("entre the no:"))
d=per(n)
if d==true:
    print("its is perfect no:")

entre the no:6
the factor of given no [1, 2, 3]
entre the no:12


NameError: name 'factor' is not defined

In [2]:
import import_ipynb
import factor
from factor import *
x=plus(4,5)
print(x)

9


# lambda fuction

In [2]:
import import_ipynb
import factor
from factor import *
s=bmi(60,170)
print(f"the bmi of man:{s}")

the bmi of man:2.0761245674740487


In [2]:
import import_ipynb
import factor
from factor import *
beby(2,5)

7

In [ ]:
# import import_ipynb
import factor
from factor import *
print(cal(3,4,"a"))

# file handling

In [5]:
f=open(r"C:\Users\nikhil pal\Desktop\myfile1.txt","a")
f.write("hi my name is nikhil pal")
f.close()

In [1]:
g=open(r"C:\Users\nikhil pal\Desktop\myfile.txt","r")
h=g.read()
print(h)

The electric eels are a genus, Electrophorus, of tropical freshwater fish from South America in the family Gymnotidae. They are electric fish, and can stun their prey by delivering shocks at up to 860 volts. Their electrical capabilities were first studied in 1775, contributing to the invention in 1800 of the electric battery. Despite their name, they are not closely related to the true eels (order Anguilliformes) but are electroreceptive knifefish (order Gymnotiformes), more closely related to catfish. Previously, the genus was believed to be monotypic, containing only Electrophorus electricus. In 2019 it was discovered that there were three species. They are nocturnal, air-breathing animals, with poor vision


In [8]:
g=open(r"C:\Users\nikhil pal\Desktop\myfile.txt","r")
h=g.read()
t=h.title()
print(t)

The Electric Eels Are A Genus, Electrophorus, Of Tropical Freshwater Fish From South America In The Family Gymnotidae. They Are Electric Fish, And Can Stun Their Prey By Delivering Shocks At Up To 860 Volts. Their Electrical Capabilities Were First Studied In 1775, Contributing To The Invention In 1800 Of The Electric Battery. Despite Their Name, They Are Not Closely Related To The True Eels (Order Anguilliformes) But Are Electroreceptive Knifefish (Order Gymnotiformes), More Closely Related To Catfish. Previously, The Genus Was Believed To Be Monotypic, Containing Only Electrophorus Electricus. In 2019 It Was Discovered That There Were Three Species. They Are Nocturnal, Air-Breathing Animals, With Poor Visioni Love You Nikhil


In [3]:
print(g)

<_io.TextIOWrapper name='C:\\Users\\nikhil pal\\Desktop\\myfile.txt' mode='r' encoding='cp1252'>


In [4]:
f=open(r"C:\Users\nikhil pal\Desktop\myfile.txt","a") # a permission is only append worlds/ no. is file
f.write("i love you nikhil")
f.close()

In [9]:
h=open (r"C:\Users\nikhil pal\Desktop\myfile1.txt","w")  # w permission is create and write world and no.
h.write("love you my self")
h.close()

In [10]:
d=open(r"C:\Users\nikhil pal\Desktop\data.txt","x")
d.write("12344556677787899836536438494509505059578575658584949049474675658549409303039438757565874894")
d.close()

In [1]:
d=open(r"C:\Users\nikhil pal\Desktop\data.txt","r")
x=d.read()
d.close()
s=0
for i in x:
    if(i.isnumeric()==True):
        number=int(i)
        s=s+number
f=open(r"C:\Users\nikhil pal\Desktop\data.txt","a")
f.write(f"\nsum of all the number in file{s}")

33

In [16]:
s=open(r"C:\Users\nikhil pal\Desktop\newdata2.txt","x")
s.write("nikhil 4000,raj 5000, rakesh 55000, bhuwan 6000")
s.close()

In [27]:
f=open(r"C:\Users\nikhil pal\Desktop\newdata1.txt","r")
content=f.read()
f.close()
print(content)

nikhil 4000 raj 5000 rakesh 55000 bhuwan 6000


In [30]:
content1=content.split(' ')

print(content)
names=[]
sellery=[]
for i in content1:
    if(i.isnumeric()==True):
        sellery.append(int(i))
    else:
        names.append(i)
print(i)
print(sellery)
max_sellery=max(sellery)
ind=sellery.index(max_sellery)
print(f"{names[ind]} has maxium sallery of {max_sellery}")
    
        

nikhil 4000 raj 5000 rakesh 55000 bhuwan 6000
6000
[4000, 5000, 55000, 6000]
rakesh has maxium sallery of 55000


In [39]:
x={
    "abhi":[10,20,30],
     "raj":[20,30,40],
     "suresh":[40,80,70]
}
student=list(x.keys())
print(student)
avg=[]
for i in x.values():
    avg.append(round(sum(i)/3))

    print(avg)

['abhi', 'raj', 'suresh']
[20]
[20, 30]
[20, 30, 63]


In [43]:
c=[]
for i in zip(student,avg):
    c.append(i)
print(dict(c))

{'abhi': 20, 'raj': 30, 'suresh': 63}


In [6]:
with open(r"C:\Users\nikhil pal\Desktop\newdata.txt","a") as f:
    f.write("nikhil")
    
    


In [9]:
import os
os.path.exists(r"C:\Users\nikhil pal\Desktop\newdata.txt")
os.remove(r"C:\Users\nikhil pal\Desktop\newdata.txt")

In [10]:
import os
os.path.exists(r"C:\Users\nikhil pal\Desktop\newdata2.txt")

True

In [11]:
import os
os.remove(r"C:\Users\nikhil pal\Desktop\newdata2.txt")

In [12]:
import os
os.mkdir(r"C:\Users\nikhil pal\Desktop\newdata5.txt")

In [16]:
f=open(r"C:\Users\nikhil pal\Desktop\newdata5.txt\nikhil","x")
f.write("love you")
f.close()

FileExistsError: [Errno 17] File exists: 'C:\\Users\\nikhil pal\\Desktop\\newdata5.txt\\nikhil'

In [4]:
import os
os.remove(r"C:\Users\nikhil pal\Desktop\newdata5.txt\nik")

# ep22 numpy

In [2]:
x=[[1,2],[3,4],[5,6]]
print(type(x))
x[0][1]


<class 'list'>


2

In [5]:
y=[
  [6,4,3],
  [1,6,7]]  



In [8]:
y[0]
    


[6, 4, 3]

In [11]:
y[1][2]

7

In [12]:
y[1]

[1, 6, 7]

In [13]:
y[0]

[6, 4, 3]

In [14]:
c=[
 [1,4,5,6],
 [5,6,7,8],
 [56,67,88,99]   
]

In [15]:
c[0][1]

4

In [16]:
c[1][3]

8

In [17]:
c[2][2]

88

In [18]:
c[0]

[1, 4, 5, 6]

In [19]:
c[1]

[5, 6, 7, 8]

In [20]:
c[2]

[56, 67, 88, 99]

In [25]:
import numpy as np
cr=np.array(c)
print(cr)

[[ 1  4  5  6]
 [ 5  6  7  8]
 [56 67 88 99]]


In [26]:
print(type(cr))

<class 'numpy.ndarray'>


In [29]:
print(cr.shape)

(3, 4)


In [30]:
print(cr.ndim)

2


In [43]:
h=np.array(cr,dtype=int)
print(h)

[[ 1  4  5  6]
 [ 5  6  7  8]
 [56 67 88 99]]


In [46]:
no_of_players=cr.shape[0]
no_of_matchs=cr.shape[1]
print(f"number of plyers:{no_of_players}")
print(f"number of matches:{no_of_matchs}")

number of plyers:3
number of matches:4


In [47]:
print(cr)

[[ 1  4  5  6]
 [ 5  6  7  8]
 [56 67 88 99]]


In [48]:
print(cr[0,1])

4


In [49]:
print(cr[0,3])

6


In [50]:
print(cr[0])

[1 4 5 6]


In [51]:
print(cr[1,0])

5


In [52]:
print(cr[1,1])

6


In [53]:
 cr

array([[ 1,  4,  5,  6],
       [ 5,  6,  7,  8],
       [56, 67, 88, 99]])

In [54]:
print(cr[1])

[5 6 7 8]


In [55]:
print(cr[2,0])

56


In [56]:
print(cr[2,2])

88


In [57]:
cr

array([[ 1,  4,  5,  6],
       [ 5,  6,  7,  8],
       [56, 67, 88, 99]])

In [58]:
print(cr[2])

[56 67 88 99]


In [60]:
print(cr[2,3])

99


# slicing

In [61]:
cr

array([[ 1,  4,  5,  6],
       [ 5,  6,  7,  8],
       [56, 67, 88, 99]])

In [64]:
x=cr[0:2,0:3]
x

array([[1, 4, 5],
       [5, 6, 7]])

In [63]:
v=cr[0:,1:]
v

array([[ 4,  5,  6],
       [ 6,  7,  8],
       [67, 88, 99]])

In [65]:
c=cr[1:,2:]
c

array([[ 7,  8],
       [88, 99]])

In [66]:
cr

array([[ 1,  4,  5,  6],
       [ 5,  6,  7,  8],
       [56, 67, 88, 99]])

In [67]:
c=[[1,2,4,5],
   [3,8,9,2],
   [6,8,9,34],
   [56,78,88,99]]

In [68]:
import numpy as np
v=np.array(c)
v

array([[ 1,  2,  4,  5],
       [ 3,  8,  9,  2],
       [ 6,  8,  9, 34],
       [56, 78, 88, 99]])

In [69]:
print(v.shape)

(4, 4)


In [70]:
print(v.ndim)

2


In [71]:
print(type(v))

<class 'numpy.ndarray'>


In [72]:
v

array([[ 1,  2,  4,  5],
       [ 3,  8,  9,  2],
       [ 6,  8,  9, 34],
       [56, 78, 88, 99]])

In [75]:
c=v[0][1]
c

2

In [76]:
g=v[0][2]
g

4

In [77]:
b=v[0][3]
b

5

In [79]:
j=v[0]
j

array([1, 2, 4, 5])

In [81]:
d=v[3][3]
d

99

In [82]:
v

array([[ 1,  2,  4,  5],
       [ 3,  8,  9,  2],
       [ 6,  8,  9, 34],
       [56, 78, 88, 99]])

In [83]:
print(v[0:,0:3])


[[ 1  2  4]
 [ 3  8  9]
 [ 6  8  9]
 [56 78 88]]


In [84]:
print(v[1:,1:3])


[[ 8  9]
 [ 8  9]
 [78 88]]


In [85]:
v

array([[ 1,  2,  4,  5],
       [ 3,  8,  9,  2],
       [ 6,  8,  9, 34],
       [56, 78, 88, 99]])

In [86]:
print(v[1:,2:])


[[ 9  2]
 [ 9 34]
 [88 99]]


In [87]:
print(v[3:])

[[56 78 88 99]]


In [88]:
v


array([[ 1,  2,  4,  5],
       [ 3,  8,  9,  2],
       [ 6,  8,  9, 34],
       [56, 78, 88, 99]])

In [89]:
print(v.sum(axis=0))

[ 66  96 110 140]


In [90]:
print(v.sum(axis=1))

[ 12  22  57 321]


# web screaping 

In [2]:
from bs4 import BeautifulSoup
import requests
import lxml
import pandas as pd
filpkart_phons={}
name_list=[]
price_list=[]
rating_list=[]
for page in range(1,10):
    url=f"https://www.flipkart.com/search?q=phon&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page={page}"

    html=requests.get(url).content
    soup=BeautifulSoup(html,"lxml")
    phons=soup.find_all('div','_3pLy-c row')

    for phon in phons:
        name=phon.find('div','_4rR01T').get_text()
        price=int(phon.find('div','_30jeq3 _1_WHN1').get_text().replace('₹','').replace(',',''))
        rating=float(phon.find('div','_3LWZlK').get_text())
        name_list.append(name)
        price_list.append(price)
        rating_list.append(rating)

filpkart_phons['name']=name_list
filpkart_phons['price']=price_list
filpkart_phons['rating']=rating_list
file=pd.DataFrame(filpkart_phons,columns=["Names","Price","Rating"])
file
                

Empty DataFrame
Columns: [Names, Price, Rating]
Index: []

# web secraping (timesjob)

In [8]:
from bs4 import BeautifulSoup
import requests
import lxml
import pandas as pd
amazon_phon={}
name_list=[]
price_list=[]
rating_list=[]
url="https://www.amazon.in/s?k=phon&crid=AXVQAVI32YIB&qid=1670435831&sprefix=phon%2Caps%2C331&ref=sr_pg_1"




<Response [503]>


In [8]:
from bs4 import BeautifulSoup
import requests
import lxml
import pandas as pd
amazon_phon={}
jobname_list=[]
sellery_list=[]
location_list=[]
experience_list=[]


url="https://www.timesjobs.com/candidate/job-search.html?from=submit&actualTxtKeywords=Data%20Science&searchBy=0&rdoOperator=OR&searchType=personalizedSearch&txtLocation=Delhi&luceneResultSize=25&postWeek=60&txtKeywords=data%20science&cboWorkExp1=0&pDate=I&sequence=1&startPage=1"
html=requests.get(url).content
soup=BeautifulSoup(html,"lxml")
job=soup.find("li""clearfix job-bx wht-shd-bx")
jobname=job.find("li","clearfix")
sellery=job.find("li","material-icons rupee")
location=job.find("li","material-icons")
experience=job.find("li","material-icons")
print(sellery)



ConnectionError: HTTPSConnectionPool(host='www.timesjobs.com', port=443): Max retries exceeded with url: /candidate/job-search.html?from=submit&actualTxtKeywords=Data%20Science&searchBy=0&rdoOperator=OR&searchType=personalizedSearch&txtLocation=Delhi&luceneResultSize=25&postWeek=60&txtKeywords=data%20science&cboWorkExp1=0&pDate=I&sequence=1&startPage=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019BD60B7D90>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))